### ISSUE TITLE
find ip for nekobox

### ISSUE THREAD

**Issue by mohamadsajjad** [Ptechgithub/warp#1]
hi, in last commit of this repo there was a file named "endip" and now i cant find it, can you help me?

**Comment by joiniran** [comment]
برار، اسکریپ اسکن برای کلود فلر رو پاک کردی نیاز داریم بهش تی فدا ؟؟؟ curl -sSL https://raw.githubusercontent.com/Ptechgithub/warp/main/endip.sh -o endip.sh && chmod +x endip.sh && ./endip.sh

**Comment by Ptechgithub** [comment]
فایل رو حذف کردم احتمالا به زودی بزارم
