### ISSUE TITLE
اسکریپت آی پی تمیز مشکل داره و کار نمیکنه پیمان جان

### ISSUE THREAD

**Issue by Mortezaw810** [Ptechgithub/warp#10]

**Comment by Ptechgithub** [comment]
bash <(curl -fsSL https://raw.githubusercontent.com/Ptechgithub/warp/main/endip/install.sh)

این اسکریپته تست کردم مشکلی نداره روی Termux تست کن

**Comment by Mortezaw810** [comment]
![Screenshot_20240324_140426.jpg](https://github.com/Ptechgithub/warp/assets/137032540/2611ccf5-a45f-4f25-8cd1-efb1f0ecd444)

اینم همون مشکل رو داره

**Comment by Ptechgithub** [comment]
از کجا termux رو دانلود کردی و مدل گوشیت چیه؟

**Comment by amir385276** [comment]
سلام پيمان جان
من هم همين مشكل رو دارم - البته مربوط به اين فورك نيست ولي توي بحث قبلي كه آپگريد شدش wireguard-go با اپديت جديد اصلا كانكشن ديگه نداريم يعني اون پراكسي 127.0.0.1 با پورت 8086 اصلا باز نميشه حتي پورت رو هم تغيير دادم و هر كلكي كه بگي سرش درآوردم.
فقط با دستور warp -e Clean IP كه از برنامه وارپ ميگيريم كار ميكنه اونهم با سرعت محدود و پائين 
من قبلا تا 70 مگ هم سرعتش كانكشن داشتم الان خيلي بكشه تا 10 مگ
احتمالا آپديت جديد مشكلاتي رو اضافه كرده و شايد باگ داشته باشه.
من به اين برنامه نويسي تسلطي ندارم. يك چيز ديگه من با هر ترفندي و روي سه گوشي مختلف شيائومي سامسونگ و هواوي و با سه خط كانكشن مختلف مخابرات و همراه اول و پارس آنلان چك كردم واقعا كانكت نميشه.
عكسش روي گوشيم هست اگر بتونم آپ ميكنم
مرسي ممنون

**Comment by Ptechgithub** [comment]
این صفحه مربوط به اسکنر وارپه . اما برای wireguard-go میتونی دستور rm -rf stuff رو بزنی و از اول اجرا کنی.

**Comment by amir385276** [comment]
باشه چشم - البته يكبار كامل اينكارو انجام دادم حتي برنامه nekobox رو تمامي ديتاهاش رو پاك كردم ولي باز هم نشد 
يكبار ديگه اجرا ميكنم ببينم چي ميشه
اگر كانكشن موفقيت آميز بود حتما يك عكس با سرعت بالا ميزارم
مرسي ممنون

**Comment by amir385276** [comment]
پيمان جان
كانكت شدش با سرعت بالا 
مرسي ممنون و واقعا خسته نباشي 
كاش روي اين مسئله مهم "نيم بها شدن ترافيك دانلود" هم يك زحمتي بكشي
هر چند مربوط به اين بحث نيست
واقعا دستت درد نكنه

**Comment by Mortezaw810** [comment]
> از کجا termux رو دانلود کردی و مدل گوشیت چیه؟

یادم نیست دقیقاً، ولی فکرکنم از fdroid
گوشیم mate 10 pro هستش

**Comment by Ptechgithub** [comment]
اسکریپت رو اپدیت کردم توضیحات رو بخونید

**Comment by amir385276** [comment]
با سلام
دوستان ترموكس خودش صفحه داره
فكر كنم ورژن 0.118.0 باشه آخرين نسخش
https://github.com/termux/termux-app/releases
