### ISSUE TITLE
Windows result file

### ISSUE THREAD

**Issue by hosseinc** [Ptechgithub/warp#11]
سلام
فایل result.csv کجا سیو میشه؟‌ تو همون پوشه نیست

**Comment by Ptechgithub** [comment]
سلام اونو زدم که حدف شه چون بهترین نتیجه رو در نهایت نمایش میده که میتونید کپی کنید

**Comment by Ptechgithub** [comment]
اضافه کردم الان نتایج ذخیره میشن داخل فایل result دانلود کنید

**Comment by hosseinc** [comment]
خیلی ممنون
