### ISSUE TITLE
گزینه ۳ مشکل خورده

### ISSUE THREAD

**Issue by mansor427** [Ptechgithub/warp#17]
![Screenshot_2024-06-01-18-00-40-256_com termux](https://github.com/Ptechgithub/warp/assets/104245967/b75263f8-0e08-4f4d-a494-150298e3ab46)

**Comment by Ptechgithub** [comment]
تست کردم مشکلی نداره احتمالا با دستگاه شما ناسازگاره میتونید از 4 استفاده کنید و بعد از نصب wire-g رو تایپ کنید.
