### ISSUE TITLE
وارد نشدن به سرور

### ISSUE THREAD

**Issue by alifathipor** [Ptechgithub/warp#2]
من اینو نصب کردم و پلاس رو زدم الان نمی تونم وارد شم به سرورم چیکار کنم

چطوری ریستارت بزنم سرور از کسه دیگه گرفته بودم

**Comment by Ptechgithub** [comment]
همچین چیزی تا حالا پیش نیومده . ببین چی رو اشتباه زدی. باید سرور رو از طریق سایتی که خریده شده ریست کنی.
