### ISSUE TITLE
Error No valid IP addresses found.

### ISSUE THREAD

**Issue by Mahantor** [Ptechgithub/warp#20]
سلام
توی همراه اول با این مشکل مواجه میشم
![Screenshot_2024-07-14-01-30-11-464-edit_com termux](https://github.com/user-attachments/assets/3fa5bad5-23e9-4451-a61f-264a359d8db0)

**Comment by Ptechgithub** [comment]
سلام روی یه نت دیگه تست کن اگه بازم این خطا رو داد کلیر دیتا کن و از اول اجرا کن
