### ISSUE TITLE
با سلام ران شدن برنامه در ویندوز راهنمایی کنید خطای 

### ISSUE THREAD

**Issue by kazempoor** [Ptechgithub/warp#7]
At line:1 char:6
+ bash <(curl -fsSL https://raw.githubusercontent.com/Ptechgithub/warp/ ...
+      ~
The '<' operator is reserved for future use.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RedirectionNotSupported
میدهد

**Comment by Ptechgithub** [comment]
روی Termux فقط اجرا کنید
